name = "oceanembed-data-proxy"
main = "worker/index.ts"
compatibility_date = "2025-09-26"

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

[vars]
SUPABASE_URL = "https://mvhtvharyruqvwmyjdqe.supabase.co"
